language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - husakJavantijan@gmail.com
    on_success: never
    on_failure: always
